In [ ]:
import pandas as pd


#What is a DataFrame?
A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

In [ ]:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


In [ ]:
#Pandas use the loc attribute to return one or more specified row(s)
#refer to the row index:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [ ]:
#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40


##With the index argument, you can name your own indexes.

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [ ]:
#Use the named index in the loc attribute to return the specified row(s).
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64


# Read CSV
A simple way to store big data sets is to use CSV files (comma separated files).

CSV files contains plain text and is a well know format that can be read by everyone including Pandas.

In [ ]:
df = pd.read_csv('data.csv')
#If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows
df
# or u can use print(df)  both are same

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
print(df.index)

RangeIndex(start=0, stop=169, step=1)


In [ ]:
#use to_string() to print the entire DataFrame.
print(df.to_string())


     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [ ]:
print(pd.options.display.max_rows)

60


In my system the number is 60, which means that if the DataFrame contains more than 60 rows, the print(df) statement will return only the headers and the first and last 5 rows.

In [ ]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('data.csv')

print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

#Viewing the Data


In [ ]:
df = pd.read_csv('data.csv')

print(df.head(10))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


In [ ]:
#Print the first 5 rows of the DataFrame:
print(df.head())



   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [ ]:
#Print the last 5 rows of the DataFrame:
print(df.tail())


     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


Info About the Data
The DataFrames object has a method called info(), that gives you more information about the data set.

In [ ]:
print(df.info()) # learn this output fully


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None


#Data Cleaning
Data cleaning means fixing bad data in your data set.

Bad data could be:
1. Empty cells
2. Data in wrong format
3. Wrong data
4. Duplicates *italicized text*

In [ ]:
#One way to deal with empty cells is to remove rows that contain empty cells.
#This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.
df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       1

In [ ]:
sum(df.isnull().any(axis=1))

0

In [ ]:
#Return a new Data Frame with no empty cells:

new_df = df.dropna()
print(new_df.to_string())


     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60   

In [ ]:
#By default, the dropna() method returns a new DataFrame, and will not change the original.
#If you want to change the original DataFrame, use the inplace = True argument:
df.dropna(inplace = True)
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60   

In [ ]:
print(df.info()) # learn this output fully


<class 'pandas.core.frame.DataFrame'>
Int64Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  164 non-null    int64  
 1   Pulse     164 non-null    int64  
 2   Maxpulse  164 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB
None


In [ ]:
sum(df.isnull().any(axis=1))

0

In [ ]:
null_df=df[df.isnull().any(axis=1)]

In [ ]:
null_df

Empty DataFrame
Columns: [Duration, Pulse, Maxpulse, Calories]
Index: []

#Replace Empty Values
Another way of dealing with empty cells is to insert a new value instead.

This way you do not have to delete entire rows just because of some empty cells.

The fillna() method allows us to replace empty cells with a value:

In [ ]:
df = pd.read_csv('data.csv')

df.fillna(130, inplace = True)

In [ ]:
df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112     130.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132     130.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137     130.0
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [ ]:
#Replace Only For Specified Columns
#To only replace empty values for one column, specify the column name for the DataFrame:
df.isnull() # any place true means null value is there


Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
5       False  False     False     False
6       False  False     False     False
7       False  False     False     False
8       False  False     False     False
9       False  False     False     False
10      False  False     False     False
11      False  False     False     False
12      False  False     False     False
13      False  False     False     False
14      False  False     False     False
15      False  False     False     False
16      False  False     False     False
17      False  False     False     False
18      False  False     False     False
19      False  False     False     False
20      False  False     False     False
21      False  False     False     False
22      False  False     False     False
23      False  False     False     False
24      False  False     False     False
25      False  False     False     False
26      False  False     False     False
27      False  False     False     False
28      False  False     False     False
29      False  False     False     False
30      False  False     False     False
31      False  False     False     False
32      False  False     False     False
33      False  False     False     False
34      False  False     False     False
35      False  False     False     False
36      False  False     False     False
37      False  False     False     False
38      False  False     False     False
39      False  False     False     False
40      False  False     False     False
41      False  False     False     False
42      False  False     False     False
43      False  False     False     False
44      False  False     False     False
45      False  False     False     False
46      False  False     False     False
47      False  False     False     False
48      False  False     False     False
49      False  False     False     False
50      False  False     False     False
51      False  False     False     False
52      False  False     False     False
53      False  False     False     False
54      False  False     False     False
55      False  False     False     False
56      False  False     False     False
57      False  False     False     False
58      False  False     False     False
59      False  False     False     False
60      False  False     False     False
61      False  False     False     False
62      False  False     False     False
63      False  False     False     False
64      False  False     False     False
65      False  False     False     False
66      False  False     False     False
67      False  False     False     False
68      False  False     False     False
69      False  False     False     False
70      False  False     False     False
71      False  False     False     False
72      False  False     False     False
73      False  False     False     False
74      False  False     False     False
75      False  False     False     False
76      False  False     False     False
77      False  False     False     False
78      False  False     False     False
79      False  False     False     False
80      False  False     False     False
81      False  False     False     False
82      False  False     False     False
83      False  False     False     False
84      False  False     False     False
85      False  False     False     False
86      False  False     False     False
87      False  False     False     False
88      False  False     False     False
89      False  False     False     False
90      False  False     False     False
91      False  False     False     False
92      False  False     False     False
93      False  False     False     False
94      False  False     False     False
95      False  False     False     False
96      False  False     Fal

In [ ]:
df.isnull().any() # co lumn wise check

Duration    False
Pulse       False
Maxpulse    False
Calories    False
dtype: bool

In [ ]:
# check again
df = pd.read_csv('data.csv')
df.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
df.isnull().any()


Duration    False
Pulse       False
Maxpulse    False
Calories     True
dtype: bool

In [ ]:
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [ ]:
print (df.isna()) # if true means null value is there


     Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
5       False  False     False     False
6       False  False     False     False
7       False  False     False     False
8       False  False     False     False
9       False  False     False     False
10      False  False     False     False
11      False  False     False     False
12      False  False     False     False
13      False  False     False     False
14      False  False     False     False
15      False  False     False     False
16      False  False     False     False
17      False  False     False      True
18      False  False     False     False
19      False  False     False     False
20      False  False     False     False
21      False  False     False     False
22      False  False     False     False
23      False  F

In [ ]:
df[df.isna().any(axis=1)] # column wise check
df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       1

In [ ]:
df[df['Calories'].isnull()] # it will display the null values in the particular column


Duration  Pulse  Maxpulse  Calories
17         45     90       112       NaN
27         60    103       132       NaN
91         45    107       137       NaN
118        60    105       125       NaN
141        60     97       127       NaN

#Replace Using Mean, Median, or Mode


In [ ]:
#Calculate the MEAN, and replace any empty values with it:

df = pd.read_csv('data.csv')

x = df["Calories"].mean()

df["Calories"].fillna(x, inplace = True)

In [ ]:
display(df.iloc[118])


Duration     60.000000
Pulse       105.000000
Maxpulse    125.000000
Calories    375.790244
Name: 118, dtype: float64

In [ ]:
print(df.iloc[118])

Duration     60.000000
Pulse       105.000000
Maxpulse    125.000000
Calories    375.790244
Name: 118, dtype: float64


In [ ]:
#Median = the value in the middle, after you have sorted all values ascending.
df = pd.read_csv('data.csv')
x = df["Calories"].median()
df["Calories"].fillna(x, inplace = True)
df.head()


Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
display(df.iloc[118])


Duration     60.0
Pulse       105.0
Maxpulse    125.0
Calories    318.6
Name: 118, dtype: float64

In [ ]:
#Calculate the MODE, and replace any empty values with it:
df = pd.read_csv('data.csv')
x = df["Calories"].mode()[0]
df["Calories"].fillna(x, inplace = True)
display(df.iloc[118])


Duration     60.0
Pulse       105.0
Maxpulse    125.0
Calories    300.0
Name: 118, dtype: float64

#Cleaning Data of Wrong Format
suppose date column is there with wrong format NaN and 20201226 ( right one is 2020/12/23)
then we have to convert it into datae format of the particular column using to_datetime()
df['Date'] = pd.to_datetime(df['Date'])
print(df.to_string())

Here NaN will be conveted into NaT

We have to remove the NULL values in date column

we have to use df.dropna(subset=['Date'], inplace = True)


# Replacing particular value in a column

That particular data only wrong means we have replace that particular value alone.

In [ ]:
#Set "Duration" = 45 in row 7:
#df.loc[7, 'Duration'] = 45


In [ ]:
df.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
#Loop through all values in the "Duration" column.
# If the value is higher than 50, set it to 48:
for x in df.index:
  if df.loc[x, "Duration"] > 50:
    df.loc[x, "Duration"] = 48

In [ ]:
df.head()

Duration  Pulse  Maxpulse  Calories
0        48    110       130     409.1
1        48    117       145     479.0
2        48    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

##Removing Rows


In [ ]:
#Delete rows where "Duration" is higher than 47:
for x in df.index:
  if df.loc[x, "Duration"] > 47:
    df.drop(x, inplace = True)


In [ ]:
df.head()

Duration  Pulse  Maxpulse  Calories
3         45    109       175     282.4
4         45    117       148     406.0
7         45    104       134     253.3
8         30    109       133     195.1
17        45     90       112       NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63 entries, 3 to 163
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  63 non-null     int64  
 1   Pulse     63 non-null     int64  
 2   Maxpulse  63 non-null     int64  
 3   Calories  61 non-null     float64
dtypes: float64(1), int64(3)
memory usage: 2.5 KB


#Removing Duplicates


In [ ]:
#Duplicate rows are rows that have been registered more than one time.

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
#Returns True for every row that is a duplicate, othwerwise False:
print(df.duplicated())


0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36      True
37      True
38      True
39     False
40      True
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71      True
72     False
73     False
74     False
75     False
76     False

In [ ]:
display(df.iloc[155])


Duration     45.0
Pulse        95.0
Maxpulse    130.0
Calories    270.0
Name: 162, dtype: float64

In [ ]:
df.drop_duplicates(inplace = True)
print(df.duplicated())


0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
39     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False

#Data Correlations
A great aspect of the Pandas module is the corr() method.

The corr() method calculates the relationship between each column in your data set.

The corr() method ignores "not numeric" columns.



In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df.corr()


Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

#Result Explained
he Result of the corr() method is a table with a lot of numbers that represents how well the relationship is between two columns.

The number varies from -1 to 1.

1 means that there is a 1 to 1 relationship (a perfect correlation), and for this data set, each time a value went up in the first column, the other one went up as well.

0.9 is also a good relationship, and if you increase one value, the other will probably increase as well.

-0.9 would be just as good relationship as 0.9, but if you increase one value, the other will probably go down.

0.2 means NOT a good relationship, meaning that if one value goes up does not mean that the other will.

# types reasons
Perfect Correlation:
We can see that "Duration" and "Duration" got the number 1.000000, which makes sense, each column always has a perfect relationship with itself.

Good Correlation:
"Duration" and "Calories" got a 0.922721 correlation, which is a very good correlation, and we can predict that the longer you work out, the more calories you burn, and the other way around: if you burned a lot of calories, you probably had a long work out.

Bad Correlation:
"Duration" and "Maxpulse" got a 0.009403 correlation, which is a very bad correlation, meaning that we can not predict the max pulse by just looking at the duration of the work out, and vice versa.

In [ ]:
#zero correlation
#Positive Correlation
#Negative Correlation

#Pandas - Plotting


In [ ]:
df.plot()